[package]
name = "synth-rs"
version = "0.1.0"
authors = ["Sebastian Ferrari <sebas5384@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.11.0"
anyhow = "1.0.26"
